frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    container_name: filament_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
