services:
  mongodb:
    image: mongo:latest
    container_name: filament_db
    restart: always
    volumes:
      - /DATA/AppData/filament_db:/data/db

  backend:
    build: ./backend
    container_name: filament_backend
    restart: always
    env_file: 
      - .env  # <-- Docker akan otomatis menyuntikkan semua variabel di .env ke backend
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: filament_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend